POST http://localhost:3000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "name": "Saurabh",
    "email": "saurabh748",
    "phnumber": "9868715540",
    "password": "123456"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "saurabh7481@gmail.com",
    "password": "12345"
}

###

POST http://localhost:3000/api/chat/send HTTP/1.1
Content-Type: application/json

{
    "message": "Hi"
}

###
 
GET http://localhost:3000/api/chat/get?lastchatid=0 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/groups/create HTTP/1.1
Content-Type: application/json

{
    "name": "First Group"
}

###

POST http://localhost:3000/api/groups/invite HTTP/1.1
Content-Type: application/json

{
    "email": "saurabh7482",
    "groupid": "1"
}

### 

GET http://localhost:3000/api/groups/get HTTP/1.1
Content-Type:  application/json

###

POST http://localhost:3000/api/groups/remove HTTP/1.1
Content-Type: application/json

{
    "email": "Email",
    "groupid": "2"
}

###

POST http://localhost:3000/api/groups/make-admin HTTP/1.1
Content-Type: application/json

{
    "email": "saurabh7482",
    "groupid": "1"
}